
CREATE TABLE TBL_MST_SUBLEVEL
(
  NUM_SUBLEVEL_ID    NUMBER,
  VCH_SUBLEVEL_NAME  VARCHAR2(100 BYTE)         NOT NULL,
  NUM_LEVEL_ID       NUMBER                     NOT NULL,
  NUM_DEPARTMENT_ID  NUMBER                     NOT NULL,
  CHR_ACTIVE_STATUS  CHAR(1 BYTE)               NOT NULL,
  DTT_CREATION_DATE  DATE                       DEFAULT SYSDATE,
  NUM_MODIFIED_BY    NUMBER,
  DTT_MODIFIED_DATE  DATE                       DEFAULT SYSDATE,
  NUM_CREATED_BY     NUMBER
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCACHE;


CREATE UNIQUE INDEX TBL_MST_SUBLEVEL_PK ON TBL_MST_SUBLEVEL
(NUM_SUBLEVEL_ID)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

ALTER TABLE TBL_MST_SUBLEVEL ADD (
  CONSTRAINT TBL_MST_SUBLEVEL_PK
  PRIMARY KEY
  (NUM_SUBLEVEL_ID)
  USING INDEX TBL_MST_SUBLEVEL_PK
  ENABLE VALIDATE);

ALTER TABLE TBL_MST_SUBLEVEL ADD (
  CONSTRAINT TBL_MST_SUBLEVEL_DEPARTID_R01 
  FOREIGN KEY (NUM_DEPARTMENT_ID) 
  REFERENCES TBL_MST_DEPARTMENT (NUM_DEPARTMENT_ID)
  ENABLE VALIDATE
,  CONSTRAINT TBL_MST_SUBLEVEL_LEVELID_R01 
  FOREIGN KEY (NUM_LEVEL_ID) 
  REFERENCES TBL_MST_LEVELS (NUM_LEVEL_ID)
  ENABLE VALIDATE);
