
CREATE TABLE TBL_MST_QUESTION
(
  NUM_QUESTION_ID           NUMBER,
  NUM_LEVEL_ID              NUMBER              NOT NULL,
  NUM_SUBLEVEL_ID           NUMBER              NOT NULL,
  VCH_QUESTION_NAME         VARCHAR2(3000 BYTE) NOT NULL,
  VCH_QUESTION_CHOICE_1     VARCHAR2(2000 BYTE) NOT NULL,
  VCH_QUESTION_TEXT_ANSWER  VARCHAR2(2000 BYTE) NOT NULL,
  NUM_CREATED_BY            NUMBER              NOT NULL,
  DTT_CREATION_DATE         DATE                DEFAULT SYSDATE,
  CHR_ACTIVE_STATUS         CHAR(1 BYTE)        NOT NULL,
  NUM_CHOICE_ANSWER         NUMBER,
  VCH_QUESTION_CHOICE_2     VARCHAR2(2000 BYTE) NOT NULL,
  VCH_QUESTION_CHOICE_3     VARCHAR2(2000 BYTE) NOT NULL,
  VCH_QUESTION_CHOICE_4     VARCHAR2(2000 BYTE) NOT NULL
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCACHE;


CREATE UNIQUE INDEX TBL_MST_QUESTION_PK ON TBL_MST_QUESTION
(NUM_QUESTION_ID)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

ALTER TABLE TBL_MST_QUESTION ADD (
  CONSTRAINT TBL_MST_QUESTION_PK
  PRIMARY KEY
  (NUM_QUESTION_ID)
  USING INDEX TBL_MST_QUESTION_PK
  ENABLE VALIDATE);

ALTER TABLE TBL_MST_QUESTION ADD (
  CONSTRAINT TBL_MST_QUESTION_CREATEDBY_R01 
  FOREIGN KEY (NUM_CREATED_BY) 
  REFERENCES TBL_MST_STAFFS (NUM_STAFF_ID)
  ENABLE VALIDATE
,  CONSTRAINT TBL_MST_QUESTION_LEVEL_ID_R01 
  FOREIGN KEY (NUM_LEVEL_ID) 
  REFERENCES TBL_MST_LEVELS (NUM_LEVEL_ID)
  ENABLE VALIDATE);
