
CREATE TABLE TBL_MST_LOGIN
(
  NUM_STUDENT_ID  NUMBER                        NOT NULL,
  VCH_USERNAME    VARCHAR2(100 BYTE)            NOT NULL,
  VCH_PASSWORD    VARCHAR2(100 BYTE)            NOT NULL,
  NUM_STAFF_ID    NUMBER                        NOT NULL,
  NUM_LOGIN_ID    NUMBER
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCACHE;


CREATE UNIQUE INDEX TBL_MST_LOGIN_PK ON TBL_MST_LOGIN
(NUM_LOGIN_ID)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

ALTER TABLE TBL_MST_LOGIN ADD (
  CONSTRAINT TBL_MST_LOGIN_PK
  PRIMARY KEY
  (NUM_LOGIN_ID)
  USING INDEX TBL_MST_LOGIN_PK
  ENABLE VALIDATE);

ALTER TABLE TBL_MST_LOGIN ADD (
  CONSTRAINT TBL_MST_LOGIN_STAFF_ID_R01 
  FOREIGN KEY (NUM_STAFF_ID) 
  REFERENCES TBL_MST_STAFFS (NUM_STAFF_ID)
  ENABLE VALIDATE
,  CONSTRAINT TBL_MST_LOGIN_STUD_ID_R01 
  FOREIGN KEY (NUM_STUDENT_ID) 
  REFERENCES TBL_MST_STUDENT (NUM_STUDENT_ID)
  ENABLE VALIDATE);
