
CREATE TABLE TBL_MST_LEVELS
(
  NUM_LEVEL_ID       NUMBER,
  VCH_LEVEL_NAME     VARCHAR2(100 BYTE)         NOT NULL,
  CHR_ACTIVE_STATUS  CHAR(1 BYTE)               NOT NULL,
  DTT_CREATION_DATE  DATE                       DEFAULT SYSDATE               NOT NULL,
  NUM_CREATED_BY     NUMBER
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCACHE;


CREATE UNIQUE INDEX TBL_MST_LEVELS_PK ON TBL_MST_LEVELS
(NUM_LEVEL_ID)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

ALTER TABLE TBL_MST_LEVELS ADD (
  CONSTRAINT TBL_MST_LEVELS_PK
  PRIMARY KEY
  (NUM_LEVEL_ID)
  USING INDEX TBL_MST_LEVELS_PK
  ENABLE VALIDATE);
