DROP TABLE TBL_MST_SCORE_PARAMETER CASCADE CONSTRAINTS;

CREATE TABLE TBL_MST_SCORE_PARAMETER
(
  NUM_SCORE_PARAMETER_ID  NUMBER,
  NUM_SCORE_FROM          NUMBER                NOT NULL,
  NUM_SCORE_TO            NUMBER                NOT NULL,
  NUM_CREATED_BY          NUMBER                NOT NULL,
  DTT_CREATION_DATE       DATE                  DEFAULT SYSDATE,
  NUM_MODIFIED_BY         NUMBER                NOT NULL,
  DTT_MODIFIED_DATE       DATE                  DEFAULT SYSDATE,
  CHR_ACTIVE_STATUS       CHAR(1 BYTE)          NOT NULL
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCACHE;


CREATE UNIQUE INDEX TBL_MST_SCORE_PARAMETER_PK ON TBL_MST_SCORE_PARAMETER
(NUM_SCORE_PARAMETER_ID)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

ALTER TABLE TBL_MST_SCORE_PARAMETER ADD (
  CONSTRAINT TBL_MST_SCORE_PARAMETER_PK
  PRIMARY KEY
  (NUM_SCORE_PARAMETER_ID)
  USING INDEX TBL_MST_SCORE_PARAMETER_PK
  ENABLE VALIDATE);
